/**
 * ISCC 自我声明：直接填充官方 PDF 表单（AcroForm）
 *
 * template/ 下的三份 PDF 都带命名字段：
 *  - ISCC_PLUS.pdf / ISCC_EU.pdf 是 ISCC 官方发布的可填写表单
 *  - ISCC.pdf（PLUS v1.2）由 scripts/build-iscc-v1-template.js 从 ISCC.docx 生成
 *
 * 流程：填文本域 → 勾复选框 → 拍平成静态内容 → 贴签名图 → 输出。
 * 表单内置 Helvetica，只能表示 Latin 字符；中文会先转拼音，其余不可编码字符被丢弃。
 *
 * 仅服务端使用（依赖 pdf-lib）。
 */
import {
  PDFDocument,
  PDFFont,
  PDFName,
  PDFRef,
  StandardFonts,
  type PDFField,
  type PDFForm,
  type PDFTextField,
} from "pdf-lib";
import { pinyin } from "pinyin-pro";
import type { IsccTemplateKey } from "@/lib/iscc-templates";

export interface IsccFormData {
  storeName: string;
  legalPerson: string;
  address: string;
  postcodeCity: string;
  cityPostcode: string;
  country: string;
  phone: string;
  geoCoordinates: string;
  position: string;
  minVolumeCheck: boolean;
  maxCapacity: string;
  maxSustainableCapacity: string;
  collectionPoint: string;
  placeDate: string;
  deliveredMaterial: string;
}

type TextFieldMap = Record<string, (data: IsccFormData) => string>;
type CheckBoxMap = Record<string, (data: IsccFormData) => boolean>;
/** 签名图位置：用表单里的某个字段矩形，或直接给页面坐标（pt，左下角原点） */
type SignaturePlacement =
  | { field: string }
  | { page: number; x: number; y: number; height: number; maxWidth: number };

interface IsccFormLayout {
  text: TextFieldMap;
  checkboxes: CheckBoxMap;
  /**
   * 「下划线填空」类字段：官方表单里这些字段的矩形比一行字高得多（底边就是下划线），
   * pdf-lib 会把文字垂直居中，看起来浮在下划线上方。列在这里的字段改为贴着下划线排（见 alignToBaseline）。
   */
  baselineFields?: string[];
  signature: SignaturePlacement;
}

/** 文本字段默认字号；单行字段放不下时按比例缩小（0.5pt 步进），与 Chrome 里手填的自动缩小效果一致 */
const FIELD_FONT_SIZE = 10;
const MIN_FONT_SIZE = 4;
/** 签名图高度（pt）。原 docx 方案里图片模块按 96dpi 的 40px 输出，即 30pt */
const SIGNATURE_HEIGHT = 30;
/** 单行字段左右各留的内边距 */
const FIELD_PADDING = 4;
/** 贴下划线排的字段统一改成这么高的一行 */
const BASELINE_FIELD_HEIGHT = 14;
/** 文字基线抬到下划线（原矩形底边）之上多少 pt；官方表单里相邻正文的基线也在底边上方约 1pt */
const BASELINE_LIFT = 1;

const FORM_LAYOUTS: Record<IsccTemplateKey, IsccFormLayout> = {
  // 由 ISCC.docx 生成的表单，字段名就是数据键；复选框在生成模板时已固定
  PLUS_V1: {
    text: {
      storeName: (d) => d.storeName,
      address: (d) => d.address,
      postcodeCity: (d) => d.postcodeCity,
      country: (d) => d.country,
      collectionPoint: (d) => d.collectionPoint,
      placeDate: (d) => d.placeDate,
    },
    checkboxes: {},
    // "Signature:" 后只贴签名图，不写姓名
    signature: { field: "signature" },
  },
  // ISCC PLUS v2.0 官方表单（3 页）
  PLUS_V2: {
    text: {
      "Site name": (d) => d.storeName,
      "Street address": (d) => d.address,
      "Postcode City Country": (d) => `${d.postcodeCity}, ${d.country}`,
      "Phone number": (d) => d.phone,
      "Geocoordinates Latitude Longitude Required format must be in decimal degrees for example XXYYYYYY XXYYYYYY":
        (d) => d.geoCoordinates,
      // "The delivered material consists of the following waste or residues" 下方的大框
      Text785: (d) => d.deliveredMaterial,
      "Recipient of the waste or residue Collecting Point": (d) => d.collectionPoint,
      // "By signing this self-declaration, I, ___"
      Text762: (d) => d.legalPerson,
      "acting in my capacity as": (d) => d.position,
      "Place Date": (d) => d.placeDate,
      // "Full name and function of signatory"
      Text763: (d) => `${d.legalPerson}, ${d.position}`,
    },
    checkboxes: {
      // 「产废量不低于 10 t/月」
      "Check Box764": (d) => d.minVolumeCheck,
      // Type of waste: Post-consumer material
      "Check Box769": () => true,
      // Raw material classification: Bio-circular
      "Check Box772": () => true,
    },
    baselineFields: ["Text762", "acting in my capacity as", "Place Date", "Text763"],
    // 官方表单没有签名域：第 3 页 "Signature:" 标签右侧（pdftotext 实测标签 x=277.6-326.9，基线 y=694.9）
    signature: { page: 2, x: 332, y: 695, height: SIGNATURE_HEIGHT, maxWidth: 225 },
  },
  // ISCC EU v2.3 官方表单（2 页）
  EU_V2: {
    text: {
      "Site Name": (d) => d.storeName,
      "Street address": (d) => d.address,
      "City Postcode": (d) => d.cityPostcode,
      Country: (d) => d.country,
      "Geocoordinates Longitude Latitude Required format must be in decimal degrees for example XXYYYYYY XXYYYYYY":
        (d) => d.geoCoordinates,
      "Phone number": (d) => d.phone,
      "Maximum estimated capacity per year in mt": (d) => d.maxCapacity,
      "Maximum estimated sustainable capacity per year in mt": (d) => d.maxSustainableCapacity,
      // 字段名取自下一行文字，实际是 "The delivered material consists of..." 下方的大框
      "The amount of waste and residues generated by the Point of Origin is five 5 or more metric tons per month":
        (d) => d.deliveredMaterial,
      "Recipient of the waste or residue Collecting Point": (d) => d.collectionPoint,
      // "By signing this self-declaration, I, ___"
      undefined: (d) => d.legalPerson,
      "and authorised representative of the Point of Origin hereby declare confirm and": (d) => d.position,
      "Place Date": (d) => d.placeDate,
      // "Full name and function of signatory"
      Text62: (d) => `${d.legalPerson}, ${d.position}`,
    },
    checkboxes: {
      // 「产废量不低于 5 t/月」
      "Check Box61": (d) => d.minVolumeCheck,
    },
    baselineFields: [
      "undefined",
      "and authorised representative of the Point of Origin hereby declare confirm and",
      "Place Date",
      "Text62",
    ],
    signature: { field: "Signature" },
  },
};

let helveticaCharset: Set<number> | null = null;

function getHelveticaCharset(font: PDFFont): Set<number> {
  if (!helveticaCharset) helveticaCharset = new Set(font.getCharacterSet());
  return helveticaCharset;
}

/**
 * 把文本变成表单字体（Helvetica / WinAnsi）能表示的形式：
 * 汉字转拼音（每个音节首字母大写），其余不可编码字符丢弃。
 */
export function toLatinText(value: string, charset: Set<number>): string {
  const transliterated = value.replace(/[㐀-鿿]+/g, (han) =>
    pinyin(han, { toneType: "none", type: "array" })
      .map((syllable) => syllable.charAt(0).toUpperCase() + syllable.slice(1))
      .join("")
  );
  let result = "";
  for (const char of transliterated) {
    const codePoint = char.codePointAt(0) ?? 0;
    if (charset.has(codePoint)) result += char;
  }
  return result.replace(/\s{2,}/g, " ").trim();
}

function findWidgetPage(pdf: PDFDocument, field: PDFField): number {
  const widget = field.acroField.getWidgets()[0];
  if (!widget) throw new Error(`Field "${field.getName()}" has no widget`);
  const widgetRef = pdf.context.getObjectRef(widget.dict);
  const pages = pdf.getPages();
  for (let index = 0; index < pages.length; index++) {
    const annots = pages[index].node.Annots();
    if (!annots) continue;
    if (annots.asArray().some((ref) => ref === widgetRef)) return index;
  }
  throw new Error(`Field "${field.getName()}" is not placed on any page`);
}

/**
 * pdf-lib 拍平后，页面 /Annots 里可能残留指向已删除控件的引用
 * （对 pdf-lib 自己创建的字段必现），poppler 会报 XRef 错误并拒绝渲染后续对象。
 */
function pruneDanglingAnnotations(pdf: PDFDocument): void {
  for (const page of pdf.getPages()) {
    const annots = page.node.Annots();
    if (!annots) continue;
    const kept = annots
      .asArray()
      .filter((ref) => !(ref instanceof PDFRef) || pdf.context.lookup(ref) !== undefined);
    if (kept.length !== annots.size()) {
      page.node.set(PDFName.of("Annots"), pdf.context.obj(kept));
    }
  }
}

/** 单行字段的字号：默认 FIELD_FONT_SIZE，放不下时按比例缩小 */
function fitFontSize(font: PDFFont, text: string, fieldWidth: number): number {
  const available = fieldWidth - FIELD_PADDING * 2;
  const natural = font.widthOfTextAtSize(text, FIELD_FONT_SIZE);
  if (natural <= available) return FIELD_FONT_SIZE;
  return Math.max(MIN_FONT_SIZE, Math.floor(((FIELD_FONT_SIZE * available) / natural) * 2) / 2);
}

/**
 * 把字段矩形改成一行高，并让文字基线落在原矩形底边（下划线）上方 BASELINE_LIFT pt。
 * pdf-lib 单行文字的基线 = rect.y + rect.height / 2 - 字体高度（不含下伸部）/ 2，与边框、内边距无关。
 */
function alignToBaseline(field: PDFTextField, font: PDFFont, fontSize: number): void {
  const widget = field.acroField.getWidgets()[0];
  const rect = widget.getRectangle();
  const glyphHeight = font.heightAtSize(fontSize, { descender: false });
  const baseline = rect.y + BASELINE_LIFT;
  widget.setRectangle({
    x: rect.x,
    y: baseline - BASELINE_FIELD_HEIGHT / 2 + glyphHeight / 2,
    width: rect.width,
    height: BASELINE_FIELD_HEIGHT,
  });
}

function fillTextFields(form: PDFForm, layout: IsccFormLayout, data: IsccFormData, font: PDFFont): void {
  const charset = getHelveticaCharset(font);
  const baselineFields = new Set(layout.baselineFields);
  for (const [fieldName, getValue] of Object.entries(layout.text)) {
    const field = form.getTextField(fieldName);
    const value = toLatinText(getValue(data), charset);
    field.setText(value);
    let fontSize = FIELD_FONT_SIZE;
    if (!field.isMultiline()) {
      const width = field.acroField.getWidgets()[0]?.getRectangle().width ?? 0;
      fontSize = fitFontSize(font, value, width);
    }
    field.setFontSize(fontSize);
    if (baselineFields.has(fieldName)) alignToBaseline(field, font, fontSize);
    field.updateAppearances(font);
  }
}

function fillCheckBoxes(form: PDFForm, layout: IsccFormLayout, data: IsccFormData): void {
  for (const [fieldName, isChecked] of Object.entries(layout.checkboxes)) {
    const checkBox = form.getCheckBox(fieldName);
    if (isChecked(data)) checkBox.check();
    else checkBox.uncheck();
  }
}

function resolveSignatureRect(
  pdf: PDFDocument,
  form: PDFForm,
  placement: SignaturePlacement
): { page: number; x: number; y: number; height: number; maxWidth: number } {
  if (!("field" in placement)) return placement;
  const field = form.getField(placement.field);
  const page = findWidgetPage(pdf, field);
  const rect = field.acroField.getWidgets()[0].getRectangle();
  // 签名域只用来定位，拍平前移除（签名域本身不能拍平）
  form.removeField(field);
  return { page, x: rect.x, y: rect.y, height: Math.min(rect.height, SIGNATURE_HEIGHT), maxWidth: rect.width };
}

async function drawSignature(
  pdf: PDFDocument,
  rect: { page: number; x: number; y: number; height: number; maxWidth: number },
  imageBytes: Uint8Array
): Promise<void> {
  const isPng =
    imageBytes.length > 4 &&
    imageBytes[0] === 0x89 &&
    imageBytes[1] === 0x50 &&
    imageBytes[2] === 0x4e &&
    imageBytes[3] === 0x47;
  const image = isPng ? await pdf.embedPng(imageBytes) : await pdf.embedJpg(imageBytes);
  let height = rect.height;
  let width = (image.width * height) / image.height;
  if (width > rect.maxWidth) {
    width = rect.maxWidth;
    height = (image.height * width) / image.width;
  }
  pdf.getPage(rect.page).drawImage(image, { x: rect.x, y: rect.y, width, height });
}

/**
 * 用一份门店数据填充 ISCC 表单模板，返回拍平后的 PDF 字节。
 */
export async function fillIsccForm(
  templateBytes: Uint8Array,
  templateKey: IsccTemplateKey,
  data: IsccFormData,
  signatureImage: Uint8Array | null
): Promise<Uint8Array> {
  const layout = FORM_LAYOUTS[templateKey];
  const pdf = await PDFDocument.load(templateBytes);
  const form = pdf.getForm();
  const font = await pdf.embedFont(StandardFonts.Helvetica);

  fillTextFields(form, layout, data, font);
  fillCheckBoxes(form, layout, data);
  const signatureRect = resolveSignatureRect(pdf, form, layout.signature);

  form.flatten();
  pruneDanglingAnnotations(pdf);
  // 签名在拍平之后再画，确保盖在字段外观之上
  if (signatureImage) await drawSignature(pdf, signatureRect, signatureImage);

  return pdf.save();
}

/** 把多份 PDF 按顺序合并成一份 */
export async function mergePdfDocuments(documents: Uint8Array[]): Promise<Uint8Array> {
  if (documents.length === 1) return documents[0];
  const merged = await PDFDocument.create();
  for (const bytes of documents) {
    const source = await PDFDocument.load(bytes);
    const pages = await merged.copyPages(source, source.getPageIndices());
    for (const page of pages) merged.addPage(page);
  }
  return merged.save();
}
